//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public string ID { get; set; }
        public string USUARIO1 { get; set; }
        public string CONTRASENIA { get; set; }
        public int ID_TIPO { get; set; }
        public bool ESTATUS { get; set; }
    
        public virtual TIPO_USUARIO TIPO_USUARIO { get; set; }
    }
}
