//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VENTA()
        {
            this.SUB_VENTA = new HashSet<SUB_VENTA>();
        }
    
        public string ID { get; set; }
        public decimal IMPORTE_TOTAL { get; set; }
        public int CANT_PRODUCTOS { get; set; }
        public System.DateTime FECHA { get; set; }
        public string ID_USUARIO { get; set; }
        public bool ESTATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUB_VENTA> SUB_VENTA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
